apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: tmp-annotations
  name: tmp-annotations
spec:
  commonName: tmp-annotations.default.svc
  dnsNames:
  - tmp-annotations.default.svc
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-cluster-issuer
  secretName: tmp-annotations
  usages:
  - server auth
  - client auth