apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tmp-annotations
  name: tmp-annotations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tmp-annotations
  template:
    metadata:
      labels:
        app: tmp-annotations
      annotations:
        kubectl.kubernetes.io/default-container: tmp-annotations
    spec:
      serviceAccountName: tmp-annotations
      containers:
      - image: harbor.mateusmuller.me/mateusmullerme/tmp-annotations:7685654-dirty
        name: tmp-annotations
        volumeMounts:
          - name: config
            mountPath: /opt/tmpant/config.yaml
            subPath: config.yaml
      - image: harbor.mateusmuller.me/mateusmullerme/tmp-annotations:7685654-dirty
        name: leader-elector
        command:
          - python
          - leaderelection.py
      volumes:
        - name: config
          configMap:
            name: tmp-annotations-config